name: Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  typecheck-and-build:
    name: Typecheck & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Log success
        run: echo "✅ Success!"

  client-build:
    name: Client SDK Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sqlite-db-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Log success
        run: echo "✅ Client SDK built!"
